name: daily report

on:
  schedule:
    - cron: '*/1 * * * *'  # Run every 2 minutes
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: first-step
        run: echo "hello nandkumar Babar"


