name: daily report

on:
  schedule:
    - cron: '1 * * * *'
  push:
    branches:
      - main  # Change this to your default branch name if needed

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: first-step
        run: echo "hello nandkumar"
